# Usa el SDK de .NET 8.0 para compilar y publicar el frontend
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build-env
WORKDIR /app

# Copia y restaura dependencias
COPY . .
RUN dotnet restore VeterinariaFronted.csproj

# Publica la aplicación en una carpeta de salida
RUN dotnet publish VeterinariaFronted.csproj -c Release -o /out

# Usa el runtime de .NET 8.0
FROM mcr.microsoft.com/dotnet/aspnet:8.0
WORKDIR /app
COPY --from=build-env /out .

# Expone el puerto de la app frontend
EXPOSE 5001

ENTRYPOINT ["dotnet", "VeterinariaFronted.dll"]