# Usa el SDK de .NET 8.0 para compilar y publicar la API
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build-env
WORKDIR /app

# Copia y restaura dependencias
COPY . .
RUN dotnet restore ApiVenta.csproj

# Publica la aplicación en una carpeta de salida
RUN dotnet publish ApiVenta.csproj -c Release -o /out

# Usa el runtime de .NET 8.0
FROM mcr.microsoft.com/dotnet/aspnet:8.0
WORKDIR /app
COPY --from=build-env /out .

# Expone el puerto de la API
EXPOSE 5000

ENTRYPOINT ["dotnet", "VeterinariaApi.dll"]